server:
  port: 8080

feign:
  hystrix:
    enabled: true

customers:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8090, http://localhost:8091, http://localhost:8092
    ServerListRefreshInterval: 15000